name: run-python-sort-script
on: pull_request
jobs:
  build:
    name: Run sort-users.py
    runs-on: ubuntu-latest
    steps:
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Sort Users
      uses: actions/checkout@v3
      run: |
        python sort-users.py
        # configure git
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git commit -a -m "(CI) format code"
        git push
