name: run-python-sort-script
on: [pull_request]
jobs:
  build:
    name: Run sort-users.py
    runs-on: ubuntu-latest
    steps:
    - name: Pull Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run script
      run: python sort-users.py
    - name: Commit files
      run: |
        git config --local user.email "matt@matt-smith.dev"
        git config --local user.name "mattcsmith"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
